[SD-1247] Refactored PR creation.

diff --git a/.github/workflows/branch-sync.yml b/.github/workflows/branch-sync.yml
--- a/.github/workflows/branch-sync.yml
+++ b/.github/workflows/branch-sync.yml
@@ -13,40 +13,85 @@ permissions:
 jobs:
   create-pull-request:
     runs-on: ubuntu-latest
+    container: ghcr.io/dpc-sdp/bay/ci-builder:pr-388
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
         with:
           ref: 6.x
 
+      - name: Set ownership of the workspace
+        run: chown -R $(id -u):$(id -g) $PWD
+
       - name: Configure git
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
-
-<<<<<<< Updated upstream
-      - name: Create a pull request from sync branch to 7.x
+      - name: Create PR
         id: create-pr
-        uses: peter-evans/create-pull-request@v7
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          base: 7.x
-          branch: temp-sync-branch
-          title: "Sync changes from 6.x"
-          body: |
-            This pull request syncs relevant changes from the `6.x` branch into the `7.x` branch.
-            
-            This PR was automatically generated by the CI workflow.
-          labels: sync, automated
-          draft: false
-          sign-commits: true
+        run: |
+          set +e
 
+          echo "stdout<<EOF" | tee "$GITHUB_OUTPUT"
+          gh pr create --base 7.x --title "Automated PR - merge 6.x into 7.x" --body "This pull request syncs relevant changes from the 6.x branch into the 7.x branch. This PR was automatically generated by the CI workflow." --label "sync" --label "automated" 2>&1 | tee -a "$GITHUB_OUTPUT" ; COMMAND_STATUS=$?
+          ( echo ; echo "EOF" ) | tee -a "$GITHUB_OUTPUT"
+          exit $COMMAND_STATUS
+        shell: bash
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Send Slack notification
-        id: notify_slack
+      - name: If successful set PR number to env var
+        if: steps.create-pr.conclusion == 'success'
+        run: |
+          output="${{ steps.create-pr.outputs.stdout }}"
+          pr=$(echo $output | grep -o "https.*[0-9]" | cut -d "/" -f 7)
+          echo "PR_NUMBER=$pr" >> $GITHUB_ENV
+
+      - name: Successful, check for conflicts
+        if: env.PR_NUMBER
+        run: |
+          conflicts=$(gh pr view ${{ env.PR_NUMBER }} --json mergeStateStatus --jq 'if .mergeStateStatus == "DIRTY" then true else false end')
+          echo "CONFLICTS=$conflicts >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: If unsuccessful parse response
+        if: always() && steps.create-pr.conclusion == 'failure'
+        run: |
+          output="${{ steps.create-pr.outputs.stdout }}"
+          no_diff=$(echo "$output" | grep -q "No commits" && echo "true" || echo "false")
+          if [[ $no_diff == "true" ]]; then
+            echo "There are no commits between the base and HEAD branches." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "FAILED=true" >> $GITHUB_ENV
+          fi
+
+      - name: Send Slack notification if pr created but conflicts exist
+        id: notify_slack_conflicts
         uses: slackapi/slack-github-action@v2.1.1
-        if: steps.create-pr.outputs.exitcode > 0
+        if: always() && env.CONFLICTS
+        env:
+          REPO_NAME: ${{ github.repository }}
+          REPO_URL: ${{ github.event.repository.html_url }}
+          LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SDP_PLATFORM_SLACK_TOKEN }}
+          payload: |
+            channel: ${{ secrets.SLACK_CHANNEL_ID }}
+            text: "GitHub Action - ${{ github.action }} requires manual intervention. \n${{ env.LINK }}"
+            blocks:
+              - type: "section"
+                text:
+                  type: "mrkdwn"
+                  text: "${{ github.action }} needs conflicts resolved." 
+          
+
+      - name: Send Slack notification if pr creation failed for a reason other than "no commits"
+        id: notify_slack_failed
+        uses: slackapi/slack-github-action@v2.1.1
+        if: always() && (steps.create-pr.conclusion == 'failure' || env.FAILED)
         env:
           REPO_NAME: ${{ github.repository }}
           REPO_URL: ${{ github.event.repository.html_url }}
@@ -57,11 +102,3 @@ jobs:
           payload: |
             channel: ${{ secrets.SLACK_CHANNEL_ID }}
             text: "GitHub Action - ${{ github.action }} failed. \n${{ env.LINK }}"
-=======
-      - name: Create PR
-        run: |
-          gh pr create --base 7.x --body "This pull request syncs relevant changes from the `6.x` branch into the `7.x` branch.\nThis PR was automatically generated by the CI workflow." --label "sync" --label "automated"
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
->>>>>>> Stashed changes
